### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by randy554** [Zeijls/web-app-from-scratch-1920#10]
https://github.com/Zeijls/web-app-from-scratch-1920/blob/f7f9a8309ac54867f62aa0e801638ceb7b57eef2/docs/js/app.js#L2

Je zou hier gebruik kunnen maken van aparte variabele om de parameters in de link aan te geven, zoals de key parameter.

**Comment by Zeijls** [comment]
ga ik nog naar kijken
