### ISSUE TITLE
Feedback naar de gebruiker

### ISSUE THREAD

**Issue by randy554** [Zeijls/web-app-from-scratch-1920#12]
https://github.com/Zeijls/web-app-from-scratch-1920/blob/f7f9a8309ac54867f62aa0e801638ceb7b57eef2/docs/index.html#L19

Je zou hier feedback aan de eindgebruiker kunnen geven met een hover effect.

**Comment by Zeijls** [comment]
Moet ik inderdaad nog toepassen. ga ik morgen naar kijken
