### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by randy554** [Zeijls/web-app-from-scratch-1920#13]
Je code ziet er verzorgd uit. De meeste functionaliteiten staan mooi in functies. 

**Rubic**

- De global scope zou nog afgebakend kunnen worden.
- Je maakt gebruik van een Promise met fetch, deze zou nog aangevuld kunnen worden met error handeling.
- Er ontbreken nog states in de app.

**Comment by Zeijls** [comment]
Error handling en states ga ik morgen toevoegen
