### ISSUE TITLE
Const of let i.p.v. var

### ISSUE THREAD

**Issue by randy554** [Zeijls/web-app-from-scratch-1920#4]
https://github.com/Zeijls/web-app-from-scratch-1920/blob/442c316fdfdc5d1dedafeca08d86fe18a8c35f5e/docs/js/app.js#L10

Voor consistentie zou je hier misschien const of let kunnen gebruiken i.p.v. een var.

**Comment by Zeijls** [comment]
heb het aangepast, thanks
