### ISSUE TITLE
Split fetch url in separate chunks

### ISSUE THREAD

**Issue by martendebruijn** [Zeijls/web-app-from-scratch-1920#8]
Voor leesbaarheid en efficiente code is het beter om je fetch url te verdelen in (herbruikbare) properties.

https://github.com/Zeijls/web-app-from-scratch-1920/blob/f7f9a8309ac54867f62aa0e801638ceb7b57eef2/docs/js/app.js#L1-L2

Bijvoorbeeld:
```js
const cors = 'https://cors-anywhere.herokuapp.com/';
const endpoint = 'https://api.anywhere.com';
const key = '42';
const url = `${cors}`${endpoint}/?key=${key};

fetch (url)

**Comment by Zeijls** [comment]
ga ik nog even naar kijken, thanks
